name: flutter_ita_greenpass
description: GreenPass reader for flutter
version: 1.0.0
repository: https://github.com/loreberti89/flutter_ita_greenpass

environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  sdk: flutter

dependecies:
  flutter:
    sdk: flutter
dev_dependencies:

   http: ^0.12.2
   http_parser: 3.1.4
   dart_base45: ^1.0.1
   archive: ^3.1.2
   equatable: ^2.0.0
   cbor: ^4.0.2
   dio: 3.0.10

